provider-loader and aggregate-providers commands
jboss-security-qe/creaper pull request #65
Opened 2017-02-08 15:07 UTC by jtymel

after last experiences.. @OndrejKotek please do not forget to submit your review ;)

2017-02-09 09:46 UTC, OndrejKotek requested changes
LGTM. `Configuration` implementation is for discussion.

2017-02-09 09:46 UTC, OndrejKotek commented on commands/src/main/java/org/wildfly/extras/creaper/commands/elytron/providerloader/AddProviderLoader.java
> +        if (configuration != null && !configuration.isEmpty()) {
What about `andObjectOptional`? `Values` can be used instead of `ModelNode`. It would be more comprehensible.

If we want to follow DMR, there should be `Configuration` inner class instead of list of `Property`...

2017-02-09 09:46 UTC, OndrejKotek commented on testsuite/standalone/src/test/java/org/wildfly/extras/creaper/commands/elytron/providerloader/AddProviderLoaderOnlineTest.java
> +        assertTrue("Second provider loader should be created", ops.exists(TEST_PROVIDER_LOADER_ADDRESS));
Existence of the second one should be tested.

2017-02-09 09:46 UTC, OndrejKotek commented on testsuite/standalone/src/test/java/org/wildfly/extras/creaper/commands/elytron/providerloader/AddProviderLoaderOnlineTest.java
> +    public void addFullProviderLoaderConfiguration() throws Exception {
Such test should be also in QE Elytron TS.

2017-02-13 12:55 UTC, jtymel commented
@OndrejKotek PTAK once more :)

2017-02-13 14:47 UTC, OndrejKotek approved these changes
LGTM

2017-02-13 14:57 UTC, jtymel commented
thanks, squashing & pushing

2017-02-14 06:43 UTC, merged